### ISSUE TITLE
Conrod example broken on macOS

### ISSUE THREAD

**Issue by jedahan** [brunocodutra/reducer#2]
macOS is frustrating. If an application wants to have a gui, that gui has to be on the main thread, as described when trying to run the conrod example.
```
▲ CXXFLAGS+=-stdlib=libc++ cargo run --release --example conrod
    Finished release [optimized] target(s) in 0.59s
     Running `target/release/examples/conrod`
thread '<unnamed>' panicked at 'Windows can only be created on the main thread on macOS', /Volumes/data/tmp/cargo/registry/src/github.com-1ecc6299db9ec823/winit-0.16.2/src/platform/macos/window.rs:595:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

I am not decent enough at threading to refactor the example to have winit on the main thread with the rest of the application in a spawned thread, but that would fix it on macOS. Maybe conrod has examples but I'm not sure.

**Comment by brunocodutra** [comment]
The joy of writing portable software. Really appreciate you running the examples and reporting back!
