### ISSUE TITLE
Consider making this project no_std + alloc

### ISSUE THREAD

**Issue by richardanaya** [brunocodutra/reducer#69]
I took a quick glance over your dependencies. There doesn't seem to be reason that jumps out to me that you couldn't make this project full on no_std + alloc if you built an executor without future-rs

**Comment by brunocodutra** [comment]
This does seem like a sensible idea.
I don't think a custom executor wouldn't even be necessary, unless you mean for the purpose of running unit tests? Likewise I suppose a custom global allocator would be necessary for the same reason.

Would you happen to be aware of a crate that does this, or maybe a tutorial somewhere, so I can have a look at how it's done properly?
